In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# New Section

In [0]:
import pandas as pd
print(pd.__version__)
data = pd.read_csv("/content/drive/My Drive/DA_Project/train.csv")
t_data = pd.read_csv("/content/drive/My Drive/DA_Project/test.csv")
print(data.shape)
print(t_data.shape)
#print(data)
#print(data.columns)
data = data.append(t_data, ignore_index = True)
data

1.0.3
(27486, 4)
(3535, 3)


textID  ... sentiment
0      a3d0a7d5ad  ...   neutral
1      251b6a6766  ...  positive
2      c9e8d1ef1c  ...   neutral
3      f14f087215  ...  negative
4      bf7473b12d  ...  positive
...           ...  ...       ...
31016  2f8444db6c  ...  negative
31017  11de8c0456  ...  negative
31018  08f6036add  ...   neutral
31019  27d6472b81  ...  negative
31020  aa1a163174  ...   neutral

[31021 rows x 4 columns]

In [0]:
def getLower(x):
  #print(x)
  if pd.isna(x):
    return ''
  return x.lower()

data = data.astype('string')
data['sentiment'] = data['sentiment'].map({'negative': -1, 'neutral': 0, 'positive': 1})
data['text'] = data['text'].map(getLower)
data['text'] = data['text'].str.replace('[^\w\s]', '')
data

textID  ... sentiment
0      a3d0a7d5ad  ...         0
1      251b6a6766  ...         1
2      c9e8d1ef1c  ...         0
3      f14f087215  ...        -1
4      bf7473b12d  ...         1
...           ...  ...       ...
31016  2f8444db6c  ...        -1
31017  11de8c0456  ...        -1
31018  08f6036add  ...         0
31019  27d6472b81  ...        -1
31020  aa1a163174  ...         0

[31021 rows x 4 columns]

In [0]:
#download punkt
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> punkt
      Unzipping tokenizers/punkt.zip.

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [0]:
data['text'] = data['text'].apply(nltk.word_tokenize)
data

textID  ... sentiment
0      a3d0a7d5ad  ...         0
1      251b6a6766  ...         1
2      c9e8d1ef1c  ...         0
3      f14f087215  ...        -1
4      bf7473b12d  ...         1
...           ...  ...       ...
31016  2f8444db6c  ...        -1
31017  11de8c0456  ...        -1
31018  08f6036add  ...         0
31019  27d6472b81  ...        -1
31020  aa1a163174  ...         0

[31021 rows x 4 columns]

In [0]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
data['text'] = data['text'].apply(lambda x: [stemmer.stem(y) for y in x])
data

textID  ... sentiment
0      a3d0a7d5ad  ...         0
1      251b6a6766  ...         1
2      c9e8d1ef1c  ...         0
3      f14f087215  ...        -1
4      bf7473b12d  ...         1
...           ...  ...       ...
31016  2f8444db6c  ...        -1
31017  11de8c0456  ...        -1
31018  08f6036add  ...         0
31019  27d6472b81  ...        -1
31020  aa1a163174  ...         0

[31021 rows x 4 columns]

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

data['text'] = data['text'].apply(lambda x: ' '.join(x))

count_vect = CountVectorizer()
counts = count_vect.fit_transform(data['text'])

In [0]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer().fit(counts)

counts = transformer.transform(counts)

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(counts, data['sentiment'], test_size=3535, shuffle=False, stratify=None)

In [0]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
print("finished training rbf")
model2 = SVC(kernel='poly')
model.fit(X_train, y_train)
model2.fit(X_train, y_train)

finished training rbf


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
import numpy as np
from sklearn.metrics import accuracy_score

predicted = model.predict(X_test)
predicted2 = model2.predict(X_test)

print(np.mean(predicted == y_test))
print(np.mean(predicted2 == y_test))
#print(accuracy_score(y_test, predicted))
#print(accuracy_score(y_test, predicted2))

0.7072135785007072
0.5626591230551626
0.7072135785007072
0.5626591230551626


In [0]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, predicted))
print(confusion_matrix(y_test, predicted2))

[[ 598  381   22]
 [ 150 1165  115]
 [  33  334  737]]
[[ 256  739    6]
 [  45 1345   40]
 [   7  709  388]]


In [0]:
from sklearn.metrics import f1_score

print(f1_score(y_test, predicted, average='micro'))
print(f1_score(y_test, predicted, average='macro'))
print(f1_score(y_test, predicted, average='weighted'))

print(f1_score(y_test, predicted2, average='micro'))
print(f1_score(y_test, predicted2, average='macro'))
print(f1_score(y_test, predicted2, average='weighted'))

0.7072135785007072
0.7067602219312997
0.7075363929594987
0.5626591230551626
0.5108925207260429
0.5260104241763665


In [0]:
from sklearn.metrics import jaccard_score

print(jaccard_score(y_test, predicted, average='micro'))
print(jaccard_score(y_test, predicted, average='macro'))
print(jaccard_score(y_test, predicted, average='weighted'))

print(jaccard_score(y_test, predicted2, average='micro'))
print(jaccard_score(y_test, predicted2, average='macro'))
print(jaccard_score(y_test, predicted2, average='weighted'))

0.5470459518599562
0.547355672406035
0.5481975396344
0.3914583743357607
0.34928154786476956
0.36326222880514114
